import { AlertTriangle, ClipboardPlus } from "lucide-react";
import { formatDateTime } from "../../lib/formatters";
import { DiagnosticFinding } from "../../types/models";
import { StatusBadge } from "../StatusBadge";

export function DiagnosticFindings({ findings, canCreateTicket, creatingTicketId, onCreateTicket }: { findings: DiagnosticFinding[]; canCreateTicket: boolean; creatingTicketId: string | null; onCreateTicket: (findingId: string) => void }) {
  return (
    <section className="device-section">
      <div className="device-section-title"><div><AlertTriangle size={18} /><span><h2>Detected Findings</h2><p>Automated findings generated by the backend diagnostics engine.</p></span></div></div>
      {findings.length === 0 ? <p className="device-empty">No diagnostic findings detected.</p> : (
        <div className="finding-list">{findings.map((finding) => (
          <article className={`finding-card ${finding.severity}`} key={finding.id}>
            <header><div><StatusBadge value={finding.severity} /><h3>{finding.title}</h3></div><StatusBadge value={finding.status} /></header>
            <p>{finding.description}</p>
            <div className="finding-detail-grid">
              <div><span>Component</span><strong>{finding.component}</strong></div>
              <div><span>Occurrence Count</span><strong>{finding.occurrence_count}</strong></div>
              <div><span>First Detected</span><strong>{formatDateTime(finding.first_detected_at)}</strong></div>
              <div><span>Last Detected</span><strong>{formatDateTime(finding.last_detected_at)}</strong></div>
            </div>
            {finding.evidence?.length > 0 && <details><summary>Evidence</summary><pre>{JSON.stringify(finding.evidence, null, 2)}</pre></details>}
            {finding.possible_cause && <div className="finding-note"><span>Possible Cause</span><p>{finding.possible_cause}</p></div>}
            {finding.recommendation && <div className="finding-note"><span>Recommendation</span><p>{finding.recommendation}</p></div>}
            {canCreateTicket && finding.status !== "resolved" && <footer><button onClick={() => onCreateTicket(finding.id)} disabled={creatingTicketId === finding.id}><ClipboardPlus size={15} /> {creatingTicketId === finding.id ? "Creating..." : "Create Repair Ticket"}</button></footer>}
          </article>
        ))}</div>
      )}
    </section>
  );
}
